{
    'name': 'FACODI Theme',
    'summary': 'Digital learning experience for Faculdade Comunitaria Digital',
    'description': 'A neo-brutalist Website and eLearning theme for FACODI.',
    'category': 'Theme/Education',
    'version': '19.0.1.1.0',
    'sequence': 120,
    'author': 'Open2 Technology (open2.tech)',
    'license': 'LGPL-3',
    'depends': [
        'website',
        'website_slides',
        'website_forum',
        'website_helpdesk',
        'website_mass_mailing',
        'website_event',
        'survey',
        'crm',
        'website_project',
        'knowledge',
        'documents',
    ],
    'data': [
        'data/generate_primary_template.xml',
        'data/ir_asset.xml',
        'data/mass_mailing.xml',
        'data/helpdesk.xml',
        'data/forum.xml',
        'data/website_menu.xml',
        'views/header.xml',
        'views/footer.xml',
        'views/homepage.xml',
        'views/pages.xml',
        'views/slides/slides_homepage.xml',
        'views/slides/slides_course.xml',
        'views/slides/slides_lesson.xml',
        'views/forum/forum_layout.xml',
        'views/forum/forum_all.xml',
        'views/forum/forum_posts.xml',
        'views/helpdesk/helpdesk_team.xml',
        'views/helpdesk/helpdesk_form.xml',
        'views/snippets/facodi_learning_hub.xml',
        'views/snippets/facodi_newsletter.xml',
    ],
    'assets': {
        'website.assets_editor': [
            'theme_facodi/static/src/js/facodi_theme_editor.js',
        ],
    },
    'images': [
        'static/description/facodi_theme_preview.svg',
    ],
    # Mapping used by the Website Configurator's SVG colour/image replacement
    # pipeline (_process_svg).  Empty dict means the palette colours are
    # applied but no image placeholders are swapped.
    'images_preview_theme': {},
    'installable': True,
}